import { createClient } from '@supabase/supabase-js'
import type { AgentOutputInsert } from '@/types/agents'

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

/**
 * Store an agent output in the database.
 */
export async function saveAgentOutput(output: AgentOutputInsert): Promise<string | null> {
  const { data, error } = await supabaseAdmin
    .from('agent_outputs')
    .insert(output)
    .select('id')
    .single()

  if (error) {
    console.error('Failed to save agent output:', error)
    return null
  }

  return data.id
}

/** Shared helper: create an EOS To-do if one with the same title isn't already open. */
export async function createAgentTodo(
  organizationId: string,
  agentName: string,
  title: string,
  detail: string,
  extra?: Record<string, unknown>
): Promise<void> {
  const { data: existing } = await supabaseAdmin
    .from('todos')
    .select('id')
    .eq('organization_id', organizationId)
    .eq('title', title)
    .eq('completed', false)
    .limit(1)

  if (existing && existing.length > 0) return

  const dueDate = new Date()
  dueDate.setDate(dueDate.getDate() + 7)

  await supabaseAdmin.from('todos').insert({
    organization_id: organizationId,
    title,
    description: `[Auto-generated by ${agentName}]\n\n${detail}`,
    completed: false,
    due_date: dueDate.toISOString().split('T')[0],
    created_by: null,
    ...extra,
  })
}

/** Shared helper: create an EOS Issue if one with the same title isn't already open. */
export async function createAgentIssue(
  organizationId: string,
  agentName: string,
  title: string,
  detail: string,
  extra?: Record<string, unknown>
): Promise<void> {
  const { data: existing } = await supabaseAdmin
    .from('issues')
    .select('id')
    .eq('organization_id', organizationId)
    .eq('title', title)
    .eq('status', 'open')
    .limit(1)

  if (existing && existing.length > 0) return

  await supabaseAdmin.from('issues').insert({
    organization_id: organizationId,
    title,
    description: `[Auto-generated by ${agentName}]\n\n${detail}`,
    status: 'open',
    priority: 1,
    created_by: null,
    ...extra,
  })
}
